name: 'Install Dependencies'
description: 'Installs Python dependencies'
inputs:
  working-directory:
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Python Greetings repo
      uses: actions/checkout@v4
      with:
        repository: 'mtararujs/python-greetings'
        path: ${{ inputs.working-directory }}

    - name: Install Python dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Installing all required dependencies..."
        pip3 install -r requirements.txt
