name: Python Greetings Delivery Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline definition
        uses: actions/checkout@v4

      - name: Checkout python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install pip dependencies
        working-directory: python-greetings
        run: |
          echo "Installing all required dependencies..."
          pip3 install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Deploy to dev environment
        uses: ./.github/actions/deploy/deploy.yml
        with:
          environment: dev
          port: 7001

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Test on dev environment
        uses: ./.github/actions/test/test.yml
        with:
          environment: dev

  deploy-to-staging:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - name: Deploy to staging environment
        uses: ./.github/actions/deploy/deploy.yml
        with:
          environment: staging
          port: 7002

  tests-on-staging:
    runs-on: self-hosted
    needs: deploy-to-staging
    steps:
      - name: Test on staging environment
        uses: ./.github/actions/test/test.yml
        with:
          environment: staging

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-staging
    steps:
      - name: Deploy to preprod environment
        uses: ./.github/actions/deploy/deploy.yml
        with:
          environment: preprod
          port: 7003

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - name: Test on preprod environment
        uses: ./.github/actions/test/test.yml
        with:
          environment: preprod

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - name: Deploy to prod environment
        uses: ./.github/actions/deploy/deploy.yml
        with:
          environment: prod
          port: 7004

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: Test on prod environment
        uses: ./.github/actions/test/test.yml
        with:
          environment: prod
