name: Python Greetings CI/CD

on:
  push:
    branches: [main]

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/install-deps
        with:
          working-directory: 'python-greetings'

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/deploy-app
        with:
          working-directory: 'python-greetings'
          env-name: 'dev'
          port: '7001'

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/run-tests
        with:
          working-directory: 'js-api-framework'
          env-name: 'dev'

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/deploy-app
        with:
          working-directory: 'python-greetings'
          env-name: 'staging'
          port: '7002'

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/run-tests
        with:
          working-directory: 'js-api-framework'
          env-name: 'staging'

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/deploy-app
        with:
          working-directory: 'python-greetings'
          env-name: 'preprod'
          port: '7003'

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/run-tests
        with:
          working-directory: 'js-api-framework'
          env-name: 'preprod'

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/deploy-app
        with:
          working-directory: 'python-greetings'
          env-name: 'prod'
          port: '7004'

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/run-tests
        with:
          working-directory: 'js-api-framework'
          env-name: 'prod'
